name: IDreamOfEasy
author: Bunnky
description: I Dream of Easy is a Slimefun Addon that implements workable community suggestions as well as other random tools and machines.
main: me.bunnky.idreamofeasy.IDreamOfEasy
website: https://github.com/Bunnky/IDreamOfEasy
version: ${project.version}
api-version: "1.20"
depend:
  - Slimefun